config: configs/config_files/ISCNet_test.yaml
data:
  ap_iou_thresh: 0.25
  c_dim: 512
  cluster_sampling: seed_fps
  completion_limit_in_train: 10
  dataset: scannet
  hidden_dim: 512
  no_height: true
  num_point: 80000
  num_target: 256
  points_subsample:
  - 1024
  - 1024
  points_unpackbits: true
  shapenet_path: datasets/ShapeNetv2_data
  skip_propagate: true
  split: datasets/splits/fullscan
  threshold: 0.5
  use_cls_for_completion: false
  use_color_completion: true
  use_color_detection: true
  vote_factor: 1
  z_dim: 32
demo:
  phase: completion
demo_path: demo/inputs/scene0549_00.off
device:
  gpu_ids: '0'
  num_workers: 0
  use_gpu: true
finetune: false
generation:
  dump_results: true
  dump_threshold: 0.5
  generate_mesh: true
  refinement_step: 0
  resolution_0: 32
  simplify_nfaces: null
  upsampling_steps: 0
  use_sampling: false
log:
  path: out/iscnet/2023-06-05T20:00:50.835190
  print_step: 10
  save_results: true
  vis_path: out/iscnet/2023-06-05T20:00:50.835190/visualization
  vis_step: 100
method: ISCNet
mode: demo
model:
  completion:
    loss: ONet_Loss
    method: ONet
    weight: 0.005
  detection:
    backbone:
      in_channels: 3
      out_channels: 64
    dense:
      cls_kernel: 9
      expand_ratio: 3
      in_channels:
      - 64
      - 128
      - 256
      - 512
      n_classes: 18
      n_reg_outs: 6
      out_channels: 64
      semantic_thr: 0.15
      use_sem_score: false
      voxel_size: 0.02
      with_yaw: false
    loss: null
    method: CAGroup3DWrapper
    post_processing:
      eval_metric: scannet
      recall_thresh_list:
      - 0.25
      - 0.5
    roi:
      code_size: 6
      coord_key: 2
      encode_sincos: false
      enlarge_ratio: false
      grid_size: 7
      middle_feature_source:
      - 3
      mlps:
      - - 64
        - 128
        - 128
      num_classes: 18
      reg_fg_thresh: 0.3
      roi_conv_kernel: 5
      roi_fg_ratio: 0.9
      roi_per_image: 128
      use_center_pooling: true
      use_grid_offset: false
      use_iou_loss: false
      use_simple_pooling: true
      voxel_size: 0.02
    semantic_iter_value: 0.02
    semantic_min_thr: 0.05
    semantic_thr: 0.15
    voxel_size: 0.02
  skip_propagation:
    loss: null
    method: SkipPropagation
resume: false
seed: 10
test:
  ap_iou_thresholds:
  - 0.5
  batch_size: 1
  conf_thresh: 0.05
  evaluate_mesh_mAP: false
  faster_eval: false
  nms_iou: 0.25
  per_class_proposal: true
  phase: completion
  use_3d_nms: true
  use_cls_nms: true
  use_old_type_nms: false
weight:
- out/pretrained_models/pretrained_weight.pth
